# Defines a default set of lint rules enforced for projects at Google. For
# details and rationale, see
# https://github.com/dart-lang/pedantic#enabled-lints.

include: package:lints/recommended.yaml

analyzer:
  exclude:
    - lib/intl/**
    - !lib/intl/localizaions.dart

linter:
  exclude:
    - lib/intl/**

