on:
  push:

jobs:
  validation:
    name: "Gradle Wrapper Validation"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
  test:
    name: "Check Dart Code"
    runs-on: ubuntu-20.04
    needs: validation
    container:
      image: google/dart:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: dart pub get
      - name: Analyze Dart
        uses: zgosalvez/github-actions-analyze-dart@v1
  build_windows:
    name: "Build Windows installers"
    runs-on: windows-2019
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dart
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install dart-sdk --no-progress
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Wix
        run: curl -fsSL https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe -o wix.exe
      - name: Install Wix
        run: .\wix.exe /install /quiet /norestart
      - uses: gradle/gradle-build-action@v1
        name: Build MSI
        env:
          DART_SDK: C:\tools\dart-sdk
        with:
          arguments: dartPubGet assembleMsi
      - name: Setup MSbuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Create Code Signing Certificate
        run: |
          New-Item -ItemType directory -Path certificate
          Set-Content -Path certificate\certificate.txt -Value '${{ secrets.WINDOWS_CERTIFICATE }}'
          certutil -decode certificate\certificate.txt certificate\certificate.pfx
      - name: Code Sign 2021
        run: |
          & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /f certificate\certificate.pfx /p '${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}' /t http://timestamp.sectigo.com/ /d McServ build/distributions/mcserv.msi
      - name: Generate Checksum
        run: (Get-FileHash ./build/distributions/mcserv.msi).Hash > mcserv.msi.sha256
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: mcserv.msi
          path: ./build/distributions/mcserv.msi
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: mcserv.msi.sha256
          path: mcserv.msi.sha256
